export { default as Deck } from './Deck'
export { default as Card } from './Card'
export { default as Details } from './Details'
export { default as Span } from './Span'
export { default as Data } from './Data'